language: bash
services: docker

script:
    - set -e
    - docker build -t $DOCKER_REPO:$TRAVIS_COMMIT .
    - export CONTAINER_ID=$(docker run -d -p 1527:1527 -v $(pwd)/dbs:/dbs $DOCKER_REPO:$TRAVIS_COMMIT)
    - while docker inspect --format "{{json .State.Health }}" $CONTAINER_ID | grep -F starting; do sleep 5; done
    - docker inspect --format "{{json .State.Health }}" $CONTAINER_ID | grep -F healthy 
    - docker logs $CONTAINER_ID | grep -F "started and ready"
    - nc -z localhost 1527
    - docker kill $CONTAINER_ID

after_success:
    - set -e
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:$([[ "$TRAVIS_BRANCH" == "master" ]] && echo "latest" || echo $TRAVIS_BRANCH)
    - docker rmi $DOCKER_REPO:$TRAVIS_COMMIT
    - docker push $DOCKER_REPO
